"""make stripe_customer_id nullable

Revision ID: cd2112d3b1df
Revises: 338108d70f7c
Create Date: 2026-04-02 20:47:26.511128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2112d3b1df'
down_revision: Union[str, Sequence[str], None] = '338108d70f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'stripe_customer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'stripe_customer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
